FROM python:3.9-slim-buster
   
   WORKDIR /app
   
   # Install any dependencies your Python functions might need
   # For example:
   # RUN pip install requests
   
   # This Dockerfile provides a base. Function code will be injected at runtime.