FROM node:16-slim
   
   WORKDIR /app
   
   # Install any dependencies
   # For example:
   # RUN npm install axios
   
   # This Dockerfile provides a base. Function code will be injected at runtime.